class_name Constants 
extends Node

#Game
const TURNS_PER_ROUND = 25
const MANA_PER_TURN = 5
const MOVE_MANA_COST = 1
const DISCARDS_PER_ROUND = 3
const BASE_HEALTH = 10
const BASE_CURRENCY = 7
const CARDS_IN_DECK = 20
const ENEMY_WAVE_SIZE = 2

#Card
const CARD_SIZE = Vector2(150, 150)
const CARD_RADIUS = 12
const CARD_SCALE_DEFAULT = Vector2(1, 1)
const CARD_SCALE_ZOOM = Vector2(1.25, 1.25)

#HAND
const HAND_SLOT_PADDING = 30

#Board
const BOARD_COLUMNS = 6
const BOARD_ROWS = 4
const BOARD_CELL_SIZE = CARD_SIZE
const BOARD_CELL_PADDING = Vector2(20, 20)

#Labels
const CURRENCY = '$'

#General Colors
var CARD_COLOR = Color.ALICE_BLUE
var DEFAULT_COLOR = Color.WHITE
var HIGHLIGHT_COLOR = Color.YELLOW
var PREVIEW_COLOR = Color.GHOST_WHITE
var TRANSPARENT_GREY = Color(1, 1, 1, 0.2)
var BORDER_GREY = Color.GRAY
var COLOR_ENERGY_GREEN = Color.GREEN
var COLOR_ENERGY_YELLOW = Color.YELLOW
var COLOR_ENERGY_PURPLE = Color.PURPLE

#Card Colors
var HERO_PORTRAIT_OUTER_COLOR = Color.BLACK
var HERO_PORTRAIT_INNER_COLOR = Color.WHITE
var HERO_PORTRAIT_BACKGROUND_COLOR = Color.BLACK
var HERO_PORTRAIT_ICON_COLOR = Color.WHITE

var HERO_NAMEPLATE_BORDER_COLOR = Color.BLACK
var HERO_NAMEPLATE_BACKGROUND_COLOR = Color.WHITE
var HERO_NAMEPLATE_FONT_COLOR =  Color.BLACK

var HERO_CLASS_NAMEPLATE_BORDER_COLOR = Color.BLACK
var HERO_CLASS_NAMEPLATE_BACKGROUND_COLOR = Color.BLACK
var HERO_CLASS_NAMEPLATE_FONT_COLOR = Color.WHITE

#Tag Colors
var TAG_COLOR_BOOSTED = Color.AQUA
var TAG_COLOR_ANTIHEAL = Color.REBECCA_PURPLE
var TAG_COLOR_DISABLED = Color.RED
var TAG_COLOR_ARMOR = Color.SLATE_GRAY

#Animation
const ANIMATION_STEP = 0.3
const ANIMATION_DELAY = 0.3
