class_name Constants 
extends Node

#Game
const TURNS_PER_ROUND = 10
const MANA_PER_TURN = 3
const DISCARDS_PER_ROUND = 3
const BASE_HEALTH = 10
const BASE_CURRENCY = 7
const CARDS_IN_DECK = 20
const ENEMY_WAVE_SIZE = 6

#Card
const CARD_SIZE = Vector2(175, 250)
const CARD_RADIUS = 12

#Labels
const CURRENCY = '$'

#General Colors
var CARD_COLOR = Color.ALICE_BLUE
var DEFAULT_COLOR = Color.WHITE
var HIGHLIGHT_COLOR = Color.HOT_PINK
var PREVIEW_COLOR = Color.GRAY
var TRANSPARENT_GREY = Color(1, 1, 1, 0.2)
var BORDER_GREY = Color.GRAY
var COLOR_ENERGY_GREEN = Color.GREEN
var COLOR_ENERGY_YELLOW = Color.YELLOW
var COLOR_ENERGY_PURPLE = Color.PURPLE

#Card Colors
var HERO_PORTRAIT_OUTER_COLOR = Color.BLACK
var HERO_PORTRAIT_INNER_COLOR = Color.WHITE
var HERO_PORTRAIT_BACKGROUND_COLOR = Color.BLACK
var HERO_PORTRAIT_ICON_COLOR = Color.WHITE

var HERO_NAMEPLATE_BORDER_COLOR = Color.BLACK
var HERO_NAMEPLATE_BACKGROUND_COLOR = Color.WHITE
var HERO_NAMEPLATE_FONT_COLOR =  Color.BLACK

var HERO_CLASS_NAMEPLATE_BORDER_COLOR = Color.BLACK
var HERO_CLASS_NAMEPLATE_BACKGROUND_COLOR = Color.BLACK
var HERO_CLASS_NAMEPLATE_FONT_COLOR = Color.WHITE

#Animation
const ANIMATION_STEP = 0.3
const ANIMATION_DELAY = 0.5
